### ISSUE TITLE
Bot script outdated?

### ISSUE THREAD

**Issue by Mrs-Feathers** [roborg-codes/telegram-mastodon-bridge#6]
Traceback (most recent call last):
  File "./bot.py", line 6, in <module>
    from bridge.bridge import Bridge
  File "/bot/bridge/bridge.py", line 16, in <module>
    class Bridge():
  File "/bot/bridge/bridge.py", line 84, in Bridge
    def __send_status(self, text: List[str], media: Optional[str | bytes] = None, mime: Optional[str] = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by roborg-codes** [comment]
True, probably bc `|` should be `Union[]` in 3.8, since `|` was introduced in 3.10 as per [PEP604](https://peps.python.org/pep-0604/).
I'll make a PR to bump up python version in Dockerfile soon.
If you are running w/o a container, you can either upgrade or try using the method below.

In the meantime, prepending each file with `from __future__ import annotations` should do the trick:
```bash
sed -i '2 i\from __future__ import annotations' ./src/app/main.py
find . -not \( -path "./venv" -prune \) -type f -not -name "__init__.py" -not -name "main.py" -name "*.py" -exec sed -i '1 i\from __future__ import annotations' {} \;
```
